# Generated by Django 4.2.7 on 2023-11-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Напишите название игры')),
                ('image', models.ImageField(upload_to='games/', verbose_name='Добавьте фото')),
                ('year', models.DateField(verbose_name='Укажите год выпуска')),
                ('director', models.CharField(max_length=100, verbose_name='Укажите разработчика')),
                ('genre', models.CharField(choices=[('Экшн', 'Экшн'), ('Хоррор', 'Хоррор'), ('Аркада', 'Аркада')], max_length=100)),
                ('description', models.TextField(blank=True, verbose_name='Описание игры')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'игру',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.CharField(max_length=100, verbose_name='Название релиза(игры)')),
                ('time', models.TimeField(verbose_name='Релиз Игры')),
                ('area', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Afisha',
        ),
        migrations.DeleteModel(
            name='FilmListModel',
        ),
    ]
