# Generated by Django 4.2.7 on 2023-11-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_gamelistmodel_release_delete_afisha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='film',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='release',
            old_name='area',
            new_name='part',
        ),
    ]
