# Generated by Django 4.2.7 on 2023-11-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_rename_film_release_game_rename_area_release_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='time',
        ),
        migrations.AddField(
            model_name='release',
            name='year',
            field=models.DateField(default=2, verbose_name='Укажите дату релиза'),
            preserve_default=False,
        ),
    ]
